from io import BytesIO
from django.contrib.auth.models import User
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase, override_settings
from PIL import Image

from .models import Category, Product, Review, Comparison, Guide


def make_image(name="test.png"):
    buf = BytesIO()
    Image.new("RGB", (64, 64), color=(200, 100, 50)).save(buf, format="PNG")
    return SimpleUploadedFile(name, buf.getvalue(), content_type="image/png")


@override_settings(MEDIA_ROOT=__import__("tempfile").mkdtemp())
class BlogTestBase(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.user = User.objects.create_user("author", password="x")
        cls.category = Category.objects.create(name="Mobile")
        cls.product = Product.objects.create(
            name="Galaxy S24 Ultra", brand="Samsung", category=cls.category
        )
        cls.review = Review.objects.create(
            product=cls.product,
            title="Review Teste",
            slug="review-teste",
            excerpt="Resumo do review.",
            content="<h2>Conteúdo</h2><p>Texto.</p>",
            main_image=make_image(),
            rating=9.0,
            pros="Bateria boa\nTela ótima",
            cons="Preço alto",
            specifications={"Processador": "Snapdragon", "RAM": ["12GB", "16GB"]},
            author=cls.user,
            is_published=True,
        )


class ModelTests(BlogTestBase):
    def test_slug_autogenerated(self):
        review = Review.objects.create(
            product=self.product,
            title="Review Sem Slug",
            excerpt="x",
            content="y",
            main_image=make_image(),
            rating=8.0,
            author=self.user,
        )
        self.assertEqual(review.slug, "review-sem-slug")

    def test_get_absolute_url(self):
        self.assertEqual(
            self.review.get_absolute_url(), f"/review/{self.review.slug}/"
        )

    def test_parsed_specs_formats_nested_values(self):
        parsed = self.review.parsed_specs
        values = {p["label"]: p["value"] for p in parsed}
        self.assertEqual(values["Processador"], "Snapdragon")
        self.assertEqual(values["RAM"], "12GB, 16GB")


class ViewTests(BlogTestBase):
    def test_home_renders_published_review(self):
        resp = self.client.get("/")
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Review Teste")

    def test_home_excludes_unpublished(self):
        Review.objects.create(
            product=self.product,
            title="Rascunho",
            excerpt="x",
            content="y",
            main_image=make_image(),
            rating=5.0,
            author=self.user,
            is_published=False,
        )
        resp = self.client.get("/")
        self.assertNotContains(resp, "Rascunho")

    def test_all_reviews_page(self):
        resp = self.client.get("/reviews/")
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Review Teste")

    def test_review_detail_has_json_ld(self):
        resp = self.client.get(self.review.get_absolute_url())
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'application/ld+json')
        self.assertContains(resp, "Galaxy S24 Ultra")

    def test_category_page(self):
        resp = self.client.get(f"/categoria/{self.category.slug}/")
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Review Teste")

    def test_categories_page(self):
        resp = self.client.get("/categorias/")
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Mobile")

    def test_comparison_detail(self):
        other = Product.objects.create(name="iPhone", brand="Apple", category=self.category)
        comparison = Comparison.objects.create(
            product_1=self.product,
            product_2=other,
            title="Duelo Teste",
            slug="duelo-teste",
            excerpt="resumo",
            content="<p>corpo</p>",
            main_image=make_image(),
            author=self.user,
            is_published=True,
        )
        resp = self.client.get(comparison.get_absolute_url())
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Duelo Teste")

    def test_guide_list(self):
        Guide.objects.create(
            title="Guia Teste",
            slug="guia-teste",
            category=self.category,
            excerpt="resumo",
            content="<p>corpo</p>",
            main_image=make_image(),
            author=self.user,
            is_published=True,
        )
        resp = self.client.get("/guias/")
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, "Guia Teste")

    def test_sitemap(self):
        resp = self.client.get("/sitemap.xml")
        self.assertEqual(resp.status_code, 200)
