# Generated by Django 6.0.3 on 2026-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Formatação igual ao conteúdo.', verbose_name='Conclusão'),
        ),
        migrations.AddField(
            model_name='review',
            name='tags_input',
            field=models.CharField(blank=True, help_text='Ex: gamer, barato, potente', max_length=255, verbose_name='Tags (separadas por vírgula)'),
        ),
    ]
