# Generated by Django 6.0.3 on 2026-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_conclusion_review_tags_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='aliexpress_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link AliExpress'),
        ),
        migrations.AddField(
            model_name='review',
            name='amazon_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Amazon'),
        ),
        migrations.AddField(
            model_name='review',
            name='kabum_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Kabum'),
        ),
        migrations.AddField(
            model_name='review',
            name='mercadolivre_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Mercado Livre'),
        ),
        migrations.AddField(
            model_name='review',
            name='shopee_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Shopee'),
        ),
    ]
