# Generated by Django 6.0.3 on 2026-03-17 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_aliexpress_link_review_amazon_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Comparativo')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('main_image', models.ImageField(upload_to='comparisons/main/', verbose_name='Imagem do Duelo')),
                ('content', models.TextField(verbose_name='Conteúdo do Comparativo (Markdown/HTML)')),
                ('verdict', models.TextField(help_text='Explique quem ganha e por que.', verbose_name='O Veredito do André')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na Home')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_first', to='reviews.product')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_second', to='reviews.product')),
            ],
            options={
                'verbose_name': 'Comparativo',
                'verbose_name_plural': 'Comparativos',
                'ordering': ['-created_at'],
            },
        ),
    ]
