# Generated by Django 6.0.3 on 2026-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='aliexpress_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link AliExpress'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='amazon_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Amazon'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='cons',
            field=models.TextField(blank=True, help_text='Um por linha', verbose_name='Pontos Negativos'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='excerpt',
            field=models.TextField(default='', help_text='Aparece nas listagens.', verbose_name='Resumo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comparison',
            name='kabum_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Kabum'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='mercadolivre_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Mercado Livre'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='pros',
            field=models.TextField(blank=True, help_text='Um por linha', verbose_name='Pontos Positivos'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Nota do Duelo (0-10)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comparison',
            name='shopee_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Shopee'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='Especificações do Duelo'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='tags',
            field=models.ManyToManyField(blank=True, to='reviews.tag'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='tags_input',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tags (separadas por vírgula)'),
        ),
    ]
