# Generated by Django 6.0.3 on 2026-03-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_comparison_aliexpress_link_comparison_amazon_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='aliexpress_link',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='amazon_link',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='kabum_link',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='mercadolivre_link',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='shopee_link',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='verdict',
        ),
        migrations.AddField(
            model_name='comparison',
            name='aliexpress_link_1',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link AliExpress (Produto 1)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='aliexpress_link_2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link AliExpress (Produto 2)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='amazon_link_1',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Amazon (Produto 1)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='amazon_link_2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Amazon (Produto 2)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='conclusion',
            field=models.TextField(blank=True, help_text='Formatação igual ao conteúdo.', verbose_name='Conclusão'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='kabum_link_1',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Kabum (Produto 1)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='kabum_link_2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Kabum (Produto 2)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='mercadolivre_link_1',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Mercado Livre (Produto 1)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='mercadolivre_link_2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Mercado Livre (Produto 2)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='shopee_link_1',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Shopee (Produto 1)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='shopee_link_2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Shopee (Produto 2)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='specifications_1',
            field=models.JSONField(blank=True, default=dict, verbose_name='Especificações Técnicas Produto 1'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='specifications_2',
            field=models.JSONField(blank=True, default=dict, verbose_name='Especificações Técnicas Produto 2'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='main_image',
            field=models.ImageField(upload_to='comparisons/main/', verbose_name='Imagem Principal'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Nota (0-10)'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='tags_input',
            field=models.CharField(blank=True, help_text='Ex: gamer, barato, potente', max_length=255, verbose_name='Tags (separadas por vírgula)'),
        ),
    ]
