# Generated by Django 6.0.3 on 2026-03-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_comparison_aliexpress_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='pros',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='specifications_1',
        ),
        migrations.RemoveField(
            model_name='comparison',
            name='specifications_2',
        ),
        migrations.AddField(
            model_name='comparison',
            name='cons_1',
            field=models.TextField(blank=True, help_text='Um por linha', verbose_name='Pontos Negativos (Produto 1)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='cons_2',
            field=models.TextField(blank=True, help_text='Um por linha', verbose_name='Pontos Negativos (Produto 2)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='pros_1',
            field=models.TextField(blank=True, help_text='Um por linha', verbose_name='Pontos Positivos (Produto 1)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='pros_2',
            field=models.TextField(blank=True, help_text='Um por linha', verbose_name='Pontos Positivos (Produto 2)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='rating_1',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Nota Produto 1 (0-10)'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='rating_2',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Nota Produto 2 (0-10)'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Nota Geral do Duelo (0-10)'),
        ),
    ]
