# Generated by Django 6.0.3 on 2026-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_comparison_cons_remove_comparison_pros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='specifications_1',
            field=models.JSONField(blank=True, default=dict, verbose_name='Especificações Técnicas Produto 1'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='specifications_2',
            field=models.JSONField(blank=True, default=dict, verbose_name='Especificações Técnicas Produto 2'),
        ),
    ]
