# Generated by Django 6.0.3 on 2026-03-19 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_comparison_specifications_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Guia')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(help_text='Aparece nas listagens.', verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo/Introdução do Guia')),
                ('conclusion', models.TextField(blank=True, verbose_name='Conclusão/Veredito Final')),
                ('main_image', models.ImageField(upload_to='guides/main/', verbose_name='Imagem Principal')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na Home')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='reviews.category')),
            ],
            options={
                'verbose_name': 'Guia de Compra',
                'verbose_name_plural': 'Guias de Compra',
            },
        ),
        migrations.CreateModel(
            name='GuideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Posição no Rank (1, 2, 3...)')),
                ('name', models.CharField(max_length=255, verbose_name='Nome de Exibição do Produto')),
                ('description', models.TextField(verbose_name='Descrição/Análise Curta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guides/items/', verbose_name='Imagem do Produto')),
                ('amazon_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Amazon')),
                ('mercadolivre_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Mercado Livre')),
                ('shopee_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Shopee')),
                ('aliexpress_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link AliExpress')),
                ('kabum_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Kabum')),
                ('pros', models.TextField(blank=True, help_text='Um por linha', verbose_name='Pontos Positivos')),
                ('cons', models.TextField(blank=True, help_text='Um por linha', verbose_name='Pontos Negativos')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reviews.guide')),
                ('product', models.ForeignKey(blank=True, help_text='Opcional: Vincule a um produto existente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.product')),
            ],
            options={
                'verbose_name': 'Item do Guia',
                'verbose_name_plural': 'Itens do Guia',
                'ordering': ['position'],
            },
        ),
    ]
