# Generated by Django 6.0.3 on 2026-08-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_guide_guideitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
