# Generated by Django 5.0.1 on 2026-09-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_create_pc_gamer_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text="Lista de dicts: [{'question': '...', 'answer': '...'}]", verbose_name='Perguntas Frequentes (FAQ)'),
        ),
    ]
