# Generated by Django 5.0.1 on 2026-09-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_create_placas_video_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='faq',
            field=models.JSONField(blank=True, default=list, verbose_name='Perguntas Frequentes'),
        ),
        migrations.AddField(
            model_name='review',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='SKU / MPN'),
        ),
    ]
